### ISSUE TITLE
wont go to my webhook

### ISSUE THREAD

**Issue by contagxx** [sinkins/VESPY-GRABBER-REUPLOADED#1]
i verified my webhook and it doesnt upload info on there even when the exe is ran. any fixes?

**Comment by VesperLmao** [comment]
u just got beamed.

**Comment by VesperLmao** [comment]
this is a shitty ass fake bro

**Comment by contagxx** [comment]
naw its not fake i had to fix something, the only thing now is the discord info. its pretty cool and its open source according to the code

**Comment by contagxx** [comment]
it also uses bat which is another reason that i know

**Comment by syntheticlol** [comment]
> this is a shitty ass fake bro

this is not fake this is my alt repo i got files directly from vesper
